name: CI/CD Testing

on:
  push:
    branches:
      - main

env:
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }} # AWS User Credentials.
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }} # AWS User Credentials.
    AWS_REGION: ap-southeast-1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Init Terraform
      run: terraform init
      working-directory: ./Terraform

    - name: Apply Terraform
      run: terraform apply -auto-approve
      working-directory: ./Terraform
    
    # - name: Destroy Terraform
    #   run: terraform destroy -auto-approve
